name: Build and Push image

on:
  push:
    branches:
      - main
      - release-[0-9]+.[0-9]+.[0-9]+*
    tags:
      - v*
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            percona/everest-catalog,enable=true
          tags: |
            type=match,pattern=v(.*),group=1
            type=match,pattern=v(\d.\d),group=1
            type=raw,value=latest,enable=true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: everest-catalog.Dockerfile
